name: 👋 Greetings

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: 👋 Welcome Contributor
    uses: dallay/common-actions/.github/workflows/greetings.yml@69060250307677655136ca88c70a2f77cb4153b2 # v2.2.4
