name: 🏷️ Sync Labels

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    name: 🏷️ Sync Labels
    uses: dallay/common-actions/.github/workflows/labels-sync.yml@v2.2.1
    with:
      labels-file: '.github/labels.yml'
    secrets: inherit